name: "ScrollLoader"

exports: "scroll-loader.js"

web: "[cpojer.net](http://cpojer.net)"
demo: http://cpojer.net/MooTools/scroll-loader/Demos/

description: "Fires an event when the user reaches a certain boundary."

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [Christoph Pojer](http://cpojer.net/)"

author: "cpojer"
authors: "[Christoph Pojer](http://cpojer.net)"
category: Request
tags: [scroll, loader, load, boundary]

sources:
    - "Source/ScrollLoader.js"
